export const TEXT = {
  cartTitle: 'Your Cart',
  cartEmptyMessage: 'Your cart is empty!',
  checkoutButton: 'Continue to Checkout',
  limitExceededMessage: 'You cannot add more than 5 of the same item.',
  cartUpdateError: 'Please fill in all the required fields.',
  productColumn: 'Product',
  imageColumn: 'Image',
  priceColumn: 'Price',
  quantityColumn: 'Quantity',
  totalColumn: 'Total',
  actionsColumn: 'Actions',
  sortByPriceLabel: 'Sort by price:',
  lowToHigh: 'Low to High',
  highToLow: 'High to Low',
  categoryLabel: 'Category',
  priceLabel: 'Price',
  addToCartButton: 'Add to Cart',
  continueToCartButton: 'Continue to Cart',
  cartLabel: 'Cart',
  unknownProduct: 'Unknown Product',
  unknownCategory: 'Unknown Category',
  unknownPrice: 'N/A',
  placeholderImage: 'https://via.placeholder.com/150',
  productQuantityUpdated: 'Cart updated.',
  productLimitExceeded: 'You cannot add more than 5 of the same item.',
  productAddedToCart: 'Product added to the cart successfully.',
  checkoutTitle: 'Checkout',
  checkoutEmpty:
    'Your cart is empty. Please add items to your cart before checking out.',
  checkoutError:
    'An error occurred while processing your request. Please try again later.',
  subtotal: 'Subtotal',
  tax: 'Tax',
  grandTotal: 'Grand Total',
  checkoutButton: 'Checkout',
  placeholderName: 'Your Name',
  placeholderEmail: 'Your Email',
  placeholderAddress: 'Your Address',
  thankYouTitle: 'Ordered Successfully!',
  thankYouMessage: 'Thank you for your order',
  thankYouShipping:
    'Your order has been successfully placed and will be shipped to',
  generalError: 'Something went wrong. Please try again later.'
};
